"""First migration

Revision ID: 906ed4e476b3
Revises:
Create Date: 2024-08-29 20:48:45.524192

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "906ed4e476b3"
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "categories",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(), nullable=True),
        sa.Column("label", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_categories_id"), "categories", ["id"], unique=False)
    op.create_table(
        "councils",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("gss", sa.String(), nullable=True),
        sa.Column("local_custodian_code", sa.BigInteger(), nullable=True),
        sa.Column("slug", sa.String(), nullable=True),
        sa.Column("country_name", sa.String(), nullable=True),
        sa.Column("homepage_url", sa.String(), nullable=True),
        sa.Column("name", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("gss"),
    )
    op.create_index(
        op.f("ix_councils_country_name"), "councils", ["country_name"], unique=False
    )
    op.create_index(op.f("ix_councils_id"), "councils", ["id"], unique=False)
    op.create_index(op.f("ix_councils_slug"), "councils", ["slug"], unique=False)
    op.create_table(
        "gp_practices_by_constituency",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("prac_code", sa.String(), nullable=True),
        sa.Column("prac_name", sa.String(), nullable=True),
        sa.Column("address1", sa.String(), nullable=True),
        sa.Column("address2", sa.String(), nullable=True),
        sa.Column("address3", sa.String(), nullable=True),
        sa.Column("address4", sa.String(), nullable=True),
        sa.Column("address5", sa.String(), nullable=True),
        sa.Column("postcode", sa.String(), nullable=True),
        sa.Column("phone", sa.String(), nullable=True),
        sa.Column("type", sa.String(), nullable=True),
        sa.Column("x", sa.BigInteger(), nullable=True),
        sa.Column("y", sa.BigInteger(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_gp_practices_by_constituency_id"),
        "gp_practices_by_constituency",
        ["id"],
        unique=False,
    )
    op.create_table(
        "mplan",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_mplan_id"), "mplan", ["id"], unique=False)
    op.create_table(
        "nhs",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("ods_code", sa.String(), nullable=True),
        sa.Column("organisation_type", sa.String(), nullable=True),
        sa.Column("organisation_name", sa.String(), nullable=True),
        sa.Column("address1", sa.String(), nullable=True),
        sa.Column("address2", sa.String(), nullable=True),
        sa.Column("address3", sa.String(), nullable=True),
        sa.Column("city", sa.String(), nullable=True),
        sa.Column("county", sa.String(), nullable=True),
        sa.Column("postcode", sa.String(), nullable=True),
        sa.Column("telephone", sa.String(), nullable=True),
        sa.Column("email", sa.String(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("ods_code"),
    )
    op.create_index(op.f("ix_nhs_id"), "nhs", ["id"], unique=False)
    op.create_table(
        "opticians",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("postcode", sa.String(), nullable=True),
        sa.Column("optician_name", sa.String(), nullable=True),
        sa.Column("address1", sa.String(), nullable=True),
        sa.Column("address2", sa.String(), nullable=True),
        sa.Column("address3", sa.String(), nullable=True),
        sa.Column("address4", sa.String(), nullable=True),
        sa.Column("telephone_number", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_opticians_id"), "opticians", ["id"], unique=False)
    op.create_table(
        "schools",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("laname", sa.String(), nullable=True),
        sa.Column("schname", sa.String(), nullable=True),
        sa.Column("street", sa.String(), nullable=True),
        sa.Column("locality", sa.String(), nullable=True),
        sa.Column("address_3", sa.String(), nullable=True),
        sa.Column("town", sa.String(), nullable=True),
        sa.Column("postcode", sa.String(), nullable=True),
        sa.Column("schstatus", sa.String(), nullable=True),
        sa.Column("minorgroup", sa.String(), nullable=True),
        sa.Column("school_type", sa.String(), nullable=True),
        sa.Column("is_primary", sa.Boolean(), nullable=True),
        sa.Column("is_secondary", sa.Boolean(), nullable=True),
        sa.Column("is_post16", sa.Boolean(), nullable=True),
        sa.Column("gender", sa.String(), nullable=True),
        sa.Column("relchar", sa.String(), nullable=True),
        sa.Column("admpol", sa.String(), nullable=True),
        sa.Column("ofsted_rating", sa.String(), nullable=True),
        sa.Column("ofsted_last_insp", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_schools_id"), "schools", ["id"], unique=False)
    op.create_table(
        "sewerages",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("constituency_code", sa.String(), nullable=True),
        sa.Column("constituency_name", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_sewerages_constituency_name"),
        "sewerages",
        ["constituency_name"],
        unique=False,
    )
    op.create_index(op.f("ix_sewerages_id"), "sewerages", ["id"], unique=False)
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_users_id"), "users", ["id"], unique=False)
    op.create_table(
        "water_supplies",
        sa.Column("id", sa.BigInteger(), autoincrement=True, nullable=False),
        sa.Column("constituency_code", sa.String(), nullable=True),
        sa.Column("constituency_name", sa.String(), nullable=True),
        sa.Column("company", sa.String(), nullable=True),
        sa.Column("website", sa.String(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(
        op.f("ix_water_supplies_constituency_name"),
        "water_supplies",
        ["constituency_name"],
        unique=False,
    )
    op.create_index(
        op.f("ix_water_supplies_id"), "water_supplies", ["id"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_water_supplies_id"), table_name="water_supplies")
    op.drop_index(
        op.f("ix_water_supplies_constituency_name"), table_name="water_supplies"
    )
    op.drop_table("water_supplies")
    op.drop_index(op.f("ix_users_id"), table_name="users")
    op.drop_table("users")
    op.drop_index(op.f("ix_sewerages_id"), table_name="sewerages")
    op.drop_index(op.f("ix_sewerages_constituency_name"), table_name="sewerages")
    op.drop_table("sewerages")
    op.drop_index(op.f("ix_schools_id"), table_name="schools")
    op.drop_table("schools")
    op.drop_index(op.f("ix_opticians_id"), table_name="opticians")
    op.drop_table("opticians")
    op.drop_index(op.f("ix_nhs_id"), table_name="nhs")
    op.drop_table("nhs")
    op.drop_index(op.f("ix_mplan_id"), table_name="mplan")
    op.drop_table("mplan")
    op.drop_index(
        op.f("ix_gp_practices_by_constituency_id"),
        table_name="gp_practices_by_constituency",
    )
    op.drop_table("gp_practices_by_constituency")
    op.drop_index(op.f("ix_councils_slug"), table_name="councils")
    op.drop_index(op.f("ix_councils_id"), table_name="councils")
    op.drop_index(op.f("ix_councils_country_name"), table_name="councils")
    op.drop_table("councils")
    op.drop_index(op.f("ix_categories_id"), table_name="categories")
    op.drop_table("categories")
    # ### end Alembic commands ###
