name: CI/CD pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

env:
  PYTHON_VERSION: '3.x'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Create and start virtual environment
        run: |
          python3 -m venv venv
          source venv/bin/activate

      - name: Install app dependencies
        run: |
          python3 -m pip install --upgrade pip
          pip install -r requirements.txt
  # TODO: UPDATE
  # lint:
  # test:
  # # deploy:
  # #   runs-on: ubuntu-latest
  # #   needs: build
